export const COLORS = {
  BACKGROUND_MAIN: '#F5EBDD',
  BACKGROUND_ELEVATED: '#FFFFFF',
  TEXT_PRIMARY: '#141A26',
  TEXT_SECONDARY: '#4E5A6B',
  ACCENT_GRADIENT_START: '#4DA1FF',
  ACCENT_GRADIENT_END: '#7AE1C3',
  SUCCESS_GREEN: '#1FBF8E',
  INACTIVE_GREY: '#CBD2DD',
  GLASS_TINT: 'rgba(255, 255, 255, 0.76)',
  GLASS_BORDER: 'rgba(20, 30, 40, 0.08)',
} as const;

export type ColorToken = keyof typeof COLORS;
